added: support for release tags (CVS)

diff --git a/source/config/makedistribution b/source/config/makedistribution
--- a/source/config/makedistribution
+++ b/source/config/makedistribution
@@ -1,15 +1,24 @@
 #!/usr/local/bin/bash
 #
-#  $Id: makedistribution,v 1.3 2000/01/17 20:39:34 oliver Exp $
+#  $Id: makedistribution,v 1.4 2000/04/25 14:45:52 oliver Exp $
 #
 
+# check whether the revision number is given as the first argument
+# (CVS tag!)
+if test $# != 1 ; then
+	echo "makdistibution <CVS tag>"
+	exit
+else
+	TAG=$1
+fi
+
 # create a dummy directory and extract the current CVS version of BALL
-echo "extracting data from cvs..."
+echo "extracting BALL revision $1 from cvs..."
 cd /tmp
 rm -fr BALL-dist 2>/dev/null
-mkdir BALL-dist 
+mkdir BALL-dist
 cd BALL-dist
-cvs co BALL >/dev/null 2>/dev/null
+cvs -q co -r ${TAG} BALL 1>cvs_extract.log 2>cvs_extract_err.log || echo "cannot extract revision ${TAG} of BALL" >&0 | exit
 # remove CVS information
 find . -name CVS -exec rm -fr {} \;
 cd BALL/source
