changed: new hierarchical test concept (experimental!)  Test are now organized in hierarchical dependent sections   (awlright - mostly!). If any test of a section fails,   no further sections are tested. This helps identifying the   source of the errors and avoids errors propagated upwards   in the test hierarchy (e.g., failure in HINFile due to   a crappy string class).   To reproduce the old behaviour (i.e., running ALL tests)   one can use the command "TEST_OPTIONS=-continue make test".

diff --git a/source/TEST/runtests b/source/TEST/runtests
--- a/source/TEST/runtests
+++ b/source/TEST/runtests
@@ -20,19 +20,49 @@ else
 	SUFFIX="\c"
 fi
 
+if test "${1}" = "-section" ; then
+	SECTION=${2}
+	shift 2
+	echo " "
+	echo "Executing tests for section ${SECTION}:"
+fi
 
-echo " "
-echo "Now running all class tests."
-echo " "
-echo "This test suite verifies that all classes included in the test"
-echo "could be correctly compiled and checks their basic functionality."
-echo "If problems occur for one of these tests, you might want to run"
-echo "this test program manually. Any failing test will be rerun with"
-echo "verbose output to identify the subtest that caused the problem."
-echo "You may run each test manually in the verbose mode by specifying -v"
-echo "on the command line."
-echo "Running these tests may take some time...."
-echo " "
+
+#
+# if -continue is given (after -section XX !)
+# the test does not abort after the first section 
+# containing failing tests
+#
+if test "${1}" = "-continue" ; then
+	ABORT_ON_FAIL=0
+	shift
+else
+	ABORT_ON_FAIL=1
+fi
+
+if test "${1}" = "-info" ; then
+	echo " "
+	echo "Now running all class tests."
+	echo " "
+	echo "This test suite verifies that all classes included in the test"
+	echo "could be correctly compiled and checks their basic functionality."
+	echo "If problems occur for one of these tests, you might want to run"
+	echo "this test program manually. Any failing test will be rerun with"
+	echo "verbose output to identify the subtest that caused the problem."
+	echo "You may run each test manually in the verbose mode by specifying -v"
+	echo "on the command line."
+	echo "Running these tests may take some time...."
+	echo " "
+	exit 0
+fi
+
+if test "${1}" = "-success" ; then
+	echo " "
+	echo "=============================================="
+	echo "All tests passed. Congratulations!"
+	echo " "
+	exit 0
+fi
 
 # remember any failed tests by setting OK=false
 OK=true
@@ -78,15 +108,12 @@ for i in $* ; do
 	COUNT=`expr ${COUNT} + 1`
 done
 
-# print some summary of all tests
-echo "====================================="
-echo " "
-
+# print some summary for failed tests
 if test "$OK" = true ; then
-	echo "All tests passed. Congratulations!"
-	echo " "
 	exit 0
 else
+	echo "============================================"
+	echo " "
 	echo "The following subtests failed:"
 
 	for i in ${FAILED_TESTS} ; do 
@@ -99,5 +126,5 @@ else
 	echo "It is also neccessary to include the files ../config.mak ../config.h"
 	echo " "
 
-	exit 1
+	exit $(ABORT_ON_FAIL)
 fi
