Clear the fallout of a rebase.

diff --git a/source/configure b/source/configure
--- a/source/configure
+++ b/source/configure
@@ -881,6 +881,7 @@ BALL_HAS_LPSOLVE
 XMKMF
 MOC
 UIC
+RCC
 SIP
 SIP_LIB
 SIP_INCLUDES
@@ -26107,7 +26108,7 @@ echo $ECHO_N "checking moc version... $ECHO_C" >&6; }
 			{ echo "$as_me:$LINENO: result: ${MOC_VERSION}" >&5
 echo "${ECHO_T}${MOC_VERSION}" >&6; }
 
-					if test "${QT_VERSION_STR}" != "${QT_VERSION_STR}" ; then
+			if test "${MOC_VERSION}" != "${QT_VERSION_STR}" ; then
 				{ echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6; }
 				{ echo "$as_me:$LINENO: result: QT version (${QT_VERSION_STR}) is incompatible with moc version (${MOC_VERSION})!" >&5
@@ -26322,7 +26323,7 @@ echo $ECHO_N "checking uic version... $ECHO_C" >&6; }
 			{ echo "$as_me:$LINENO: result: ${UIC_VERSION}" >&5
 echo "${ECHO_T}${UIC_VERSION}" >&6; }
 
-					if test "${QT_VERSION_STR}" != "${QT_VERSION_STR}" ; then
+			if test "${UIC_VERSION}" != "${QT_VERSION_STR}" ; then
 				{ echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6; }
 				{ echo "$as_me:$LINENO: result: QT version (${QT_VERSION_STR}) is incompatible with uic version (${UIC_VERSION})!" >&5
@@ -26333,6 +26334,217 @@ echo "${ECHO_T}Please check your QTDIR environment variable, include the correct
 echo "${ECHO_T}path to uic in your PATH environment variable, or specify the correct" >&6; }
 				{ echo "$as_me:$LINENO: result: path to uic using the option --with-uic=PATH to rerun configure." >&5
 echo "${ECHO_T}path to uic using the option --with-uic=PATH to rerun configure." >&6; }
+
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+	{ echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6; }
+	{ echo "$as_me:$LINENO: result: of the above error message, please contact the BALL mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the BALL mailing list" >&6; }
+	{ echo "$as_me:$LINENO: result: or the BALL developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the BALL developers. Please enclose the file 'conf.diag.tar'" >&6; }
+	{ echo "$as_me:$LINENO: result: which has been created in source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in source. It contains the relevant" >&6; }
+	{ echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6; }
+	{ echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6; }
+	{ echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6; }
+	{ echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6; }
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+	FILES="configure configure.ac aclocal.m4 config.log"
+	if test -f config.h ; then FILES="$FILES config.h" ; fi
+	if test -f config.mak ; then FILES="$FILES config.mak" ; fi
+	if test -f common.mak ; then FILES="$FILES common.mak" ; fi
+	tar cf $TARFILE $FILES
+
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+			fi
+		fi
+	fi
+
+					if test "${USE_VIEW}" = true ; then
+		if test "${RCC}" = rcc ; then
+			if test "${QTDIR}" != "" ; then
+				RCC=${QTDIR}/bin/rcc
+			fi
+		fi
+
+								# Extract the first word of "rcc", so it can be a program name with args.
+set dummy rcc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_RCC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $RCC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_RCC="$RCC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_RCC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_RCC" && ac_cv_path_RCC="rcc"
+  ;;
+esac
+fi
+RCC=$ac_cv_path_RCC
+if test -n "$RCC"; then
+  { echo "$as_me:$LINENO: result: $RCC" >&5
+echo "${ECHO_T}$RCC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+		if test "${RCC}" = rcc ; then
+			{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+			{ echo "$as_me:$LINENO: result: Could not find the QT Meta Object Compiler (rcc)!" >&5
+echo "${ECHO_T}Could not find the QT Meta Object Compiler (rcc)!" >&6; }
+			{ echo "$as_me:$LINENO: result: You might run into trouble if you want to compile MolVIEW." >&5
+echo "${ECHO_T}You might run into trouble if you want to compile MolVIEW." >&6; }
+			{ echo "$as_me:$LINENO: result: Please include the correct path to rcc into your" >&5
+echo "${ECHO_T}Please include the correct path to rcc into your" >&6; }
+			{ echo "$as_me:$LINENO: result: PATH environment variable or specify the path to moc" >&5
+echo "${ECHO_T}PATH environment variable or specify the path to moc" >&6; }
+			{ echo "$as_me:$LINENO: result: using the option --with-rcc=PATH to rerun configure." >&5
+echo "${ECHO_T}using the option --with-rcc=PATH to rerun configure." >&6; }
+
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+	{ echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6; }
+	{ echo "$as_me:$LINENO: result: of the above error message, please contact the BALL mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the BALL mailing list" >&6; }
+	{ echo "$as_me:$LINENO: result: or the BALL developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the BALL developers. Please enclose the file 'conf.diag.tar'" >&6; }
+	{ echo "$as_me:$LINENO: result: which has been created in source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in source. It contains the relevant" >&6; }
+	{ echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6; }
+	{ echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6; }
+	{ echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6; }
+	{ echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6; }
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+	FILES="configure configure.ac aclocal.m4 config.log"
+	if test -f config.h ; then FILES="$FILES config.h" ; fi
+	if test -f config.mak ; then FILES="$FILES config.mak" ; fi
+	if test -f common.mak ; then FILES="$FILES common.mak" ; fi
+	tar cf $TARFILE $FILES
+
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+		fi
+            		{ echo "$as_me:$LINENO: checking whether we can run rcc" >&5
+echo $ECHO_N "checking whether we can run rcc... $ECHO_C" >&6; }
+    if test ! -x "${RCC}" ; then
+			{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+			{ echo "$as_me:$LINENO: result: The QT Resource Compiler (rcc) found in " >&5
+echo "${ECHO_T}The QT Resource Compiler (rcc) found in " >&6; }
+      { echo "$as_me:$LINENO: result: \"  ${RCC}\"" >&5
+echo "${ECHO_T}\"  ${RCC}\"" >&6; }
+      { echo "$as_me:$LINENO: result: seems not to be an executable!" >&5
+echo "${ECHO_T}seems not to be an executable!" >&6; }
+			{ echo "$as_me:$LINENO: result: Please include the correct path to rcc into your" >&5
+echo "${ECHO_T}Please include the correct path to rcc into your" >&6; }
+			{ echo "$as_me:$LINENO: result: PATH environment variable or specify the path to rcc" >&5
+echo "${ECHO_T}PATH environment variable or specify the path to rcc" >&6; }
+			{ echo "$as_me:$LINENO: result: using the option --with-rcc=PATH to rerun configure." >&5
+echo "${ECHO_T}using the option --with-rcc=PATH to rerun configure." >&6; }
+
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+	{ echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6; }
+	{ echo "$as_me:$LINENO: result: of the above error message, please contact the BALL mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the BALL mailing list" >&6; }
+	{ echo "$as_me:$LINENO: result: or the BALL developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the BALL developers. Please enclose the file 'conf.diag.tar'" >&6; }
+	{ echo "$as_me:$LINENO: result: which has been created in source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in source. It contains the relevant" >&6; }
+	{ echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6; }
+	{ echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6; }
+	{ echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6; }
+	{ echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6; }
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+	FILES="configure configure.ac aclocal.m4 config.log"
+	if test -f config.h ; then FILES="$FILES config.h" ; fi
+	if test -f config.mak ; then FILES="$FILES config.mak" ; fi
+	if test -f common.mak ; then FILES="$FILES common.mak" ; fi
+	tar cf $TARFILE $FILES
+
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+		else
+			{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+			{ echo "$as_me:$LINENO: checking rcc version" >&5
+echo $ECHO_N "checking rcc version... $ECHO_C" >&6; }
+			RCC_VERSION=`${RCC} -v 2>&1 | ${TR} -d "()" | ${SED} "s/.* Qt //" | ${SED} "s/-.*//"`
+			{ echo "$as_me:$LINENO: result: ${RCC_VERSION}" >&5
+echo "${ECHO_T}${RCC_VERSION}" >&6; }
+
+					if test "${QT_VERSION_STR}" != "${QT_VERSION_STR}" ; then
+				{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+				{ echo "$as_me:$LINENO: result: QT version (${QT_VERSION_STR}) is incompatible with moc version (${RCC_VERSION})!" >&5
+echo "${ECHO_T}QT version (${QT_VERSION_STR}) is incompatible with moc version (${RCC_VERSION})!" >&6; }
+				{ echo "$as_me:$LINENO: result: Please check your QTDIR environment variable, include the correct" >&5
+echo "${ECHO_T}Please check your QTDIR environment variable, include the correct" >&6; }
+				{ echo "$as_me:$LINENO: result: path to moc in your PATH environment variable, or specify the correct" >&5
+echo "${ECHO_T}path to moc in your PATH environment variable, or specify the correct" >&6; }
+				{ echo "$as_me:$LINENO: result: path to moc using the option --with-rcc=PATH to rerun configure." >&5
+echo "${ECHO_T}path to moc using the option --with-rcc=PATH to rerun configure." >&6; }
 
 	{ echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6; }
@@ -28052,13 +28264,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:28055: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:28267: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:28058: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:28270: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:28061: output\"" >&5)
+  (eval echo "\"\$as_me:28273: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -29157,7 +29369,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 29160 "configure"' > conftest.$ac_ext
+  echo '#line 29372 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -31130,11 +31342,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31133: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31345: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:31137: \$? = $ac_status" >&5
+   echo "$as_me:31349: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -31454,11 +31666,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31457: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31669: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:31461: \$? = $ac_status" >&5
+   echo "$as_me:31673: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -31559,11 +31771,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31562: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31774: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:31566: \$? = $ac_status" >&5
+   echo "$as_me:31778: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31614,11 +31826,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31617: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31829: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:31621: \$? = $ac_status" >&5
+   echo "$as_me:31833: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -34375,7 +34587,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 34378 "configure"
+#line 34590 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -34475,7 +34687,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 34478 "configure"
+#line 34690 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -36478,11 +36690,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36481: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36693: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:36485: \$? = $ac_status" >&5
+   echo "$as_me:36697: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -36577,11 +36789,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36580: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:36584: \$? = $ac_status" >&5
+   echo "$as_me:36796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -36629,11 +36841,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36632: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36844: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:36636: \$? = $ac_status" >&5
+   echo "$as_me:36848: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -38881,6 +39093,7 @@ BALL_HAS_LPSOLVE!$BALL_HAS_LPSOLVE$ac_delim
 XMKMF!$XMKMF$ac_delim
 MOC!$MOC$ac_delim
 UIC!$UIC$ac_delim
+RCC!$RCC$ac_delim
 SIP!$SIP$ac_delim
 SIP_LIB!$SIP_LIB$ac_delim
 SIP_INCLUDES!$SIP_INCLUDES$ac_delim
@@ -38957,7 +39170,6 @@ LIBDIR!$LIBDIR$ac_delim
 ADDITIONAL_COMMENTS!$ADDITIONAL_COMMENTS$ac_delim
 USE_VIEW!$USE_VIEW$ac_delim
 BALL_HAS_VIEW!$BALL_HAS_VIEW$ac_delim
-VIEW_PLATFORM!$VIEW_PLATFORM$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -38999,6 +39211,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+VIEW_PLATFORM!$VIEW_PLATFORM$ac_delim
 LIBVIEW!$LIBVIEW$ac_delim
 TEMPLATE_DIR!$TEMPLATE_DIR$ac_delim
 SUBDIRS!$SUBDIRS$ac_delim
@@ -39006,7 +39219,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
