added QtSql lib

diff --git a/source/configure b/source/configure
--- a/source/configure
+++ b/source/configure
@@ -20746,6 +20746,162 @@ echo "$as_me: error: Aborted." >&2;}
 		fi
 	fi
 
+	{ echo "$as_me:$LINENO: checking for libQtSql" >&5
+echo $ECHO_N "checking for libQtSql... $ECHO_C" >&6; }
+	if test "${QTDIR}" != "" ; then
+		if test -a "${QTDIR}/lib/libQtSql.so" ; then
+			QT_LIBPATH="${QTDIR}/lib"
+			{ echo "$as_me:$LINENO: result: (${QT_LIBPATH})" >&5
+echo "${ECHO_T}(${QT_LIBPATH})" >&6; }
+		fi
+		if test "${QT_LIBPATH}" = "" ; then
+
+	_LIBS=
+
+		if test "${QT_LIBPATH}" != "" ; then
+		_LIBS=${QT_LIBPATH}
+	fi
+
+	if test "${QTDIR}/lib ${QTDIR}/lib/${BINFMT} ${BALL_PATH}/contrib/lib" = "" ; then
+		_LIBDIRS="/usr/lib /opt/lib /usr/local/lib"
+	else
+		_LIBDIRS="${QTDIR}/lib ${QTDIR}/lib/${BINFMT} ${BALL_PATH}/contrib/lib"
+	fi
+
+	if test "${_LIBS}" = "" ; then
+		for i in ${_LIBDIRS} ; do
+			for j in $i/libQtSql.* ; do
+				if test -f "$j" -a "${_LIBS}" = ""; then
+					_LIBS="$i"
+				fi
+			done
+		done
+	fi
+
+	if test "${_LIBS}" = "" ; then
+		for i in /usr/lib /opt/lib /usr/*/lib /opt/*/lib ; do
+			for j in $i/libQtSql.* ; do
+				if test -f "$j" -a "${_LIBS}" = ""; then
+					_LIBS="$i"
+				fi
+			done
+		done
+	fi
+
+	if test "${_LIBS}" = "" ; then
+		for i in /opt/*/*/lib /usr/*/*/lib /usr/local/*/*/lib ; do
+			for j in $i/libQtSql.* ; do
+				if test -f "$j" -a "${_LIBS}" = ""; then
+					_LIBS="$i"
+				fi
+			done
+		done
+	fi
+
+	if test "${_LIBS}" = "" -a "${FIND}" != "-" ; then
+		if test "${_LIBS}" = "" -a "${QTDIR}/lib ${QTDIR}/lib/${BINFMT} ${BALL_PATH}/contrib/lib" != ""; then
+			for i in ${QTDIR}/lib ${QTDIR}/lib/${BINFMT} ${BALL_PATH}/contrib/lib /dev/null; do
+				if test "${_LIBS}" = "" ; then
+					_TMP=`${FIND} $i -name "libQtSql.*" -print 2>/dev/null`
+					for j in ${_TMP} ; do
+						if test "${_LIBS}" = "" ; then
+							_LIBS=`echo $j|${SED} "s/\/libQtSql\\.*/\//"`
+						fi
+					done
+				fi
+			done
+		fi
+
+		if test "${_LIBS}" = "" ; then
+			_TMP=`${FIND} /opt -name "libQtSql.*" -print 2>/dev/null`
+			for j in ${_TMP} ; do
+				if test "${_LIBS}" = "" ; then
+					_LIBS=`echo $j|${SED} "s/\/libQtSql\\.*/\//"`
+				fi
+			done
+		fi
+
+		if test "${_LIBS}" = "" ; then
+			_TMP=`${FIND} /usr -name "libQtSql.*" -print 2>/dev/null`
+			for j in ${_TMP} ; do
+				if test "${_LIBS}" = "" ; then
+					_LIBS=`echo $j|${SED} "s/\/libQtSql\\.*/\//"`
+				fi
+			done
+		fi
+
+	fi
+
+	QT_LIBPATH="${_LIBS}"
+
+			{ echo "$as_me:$LINENO: result: (${QT_LIBPATH})" >&5
+echo "${ECHO_T}(${QT_LIBPATH})" >&6; }
+		fi
+		if test "${QT_LIBPATH}" = "" ; then
+			{ echo "$as_me:$LINENO: result: (not found!)" >&5
+echo "${ECHO_T}(not found!)" >&6; }
+			{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+			{ echo "$as_me:$LINENO: result: The QtSql library could not be found. Please specify the path to libqt" >&5
+echo "${ECHO_T}The QtSql library could not be found. Please specify the path to libqt" >&6; }
+			{ echo "$as_me:$LINENO: result: by passing the option --with-qt-libs=DIR to configure." >&5
+echo "${ECHO_T}by passing the option --with-qt-libs=DIR to configure." >&6; }
+			{ echo "$as_me:$LINENO: result: You may also set the environment variable QTDIR to the correct" >&5
+echo "${ECHO_T}You may also set the environment variable QTDIR to the correct" >&6; }
+			{ echo "$as_me:$LINENO: result: path - configure will recognize this, too." >&5
+echo "${ECHO_T}path - configure will recognize this, too." >&6; }
+			{ echo "$as_me:$LINENO: result: If the QT library was built with thread support enabled (libqt-mt" >&5
+echo "${ECHO_T}If the QT library was built with thread support enabled (libqt-mt" >&6; }
+			{ echo "$as_me:$LINENO: result: instead of libqt), please specify the option --with-threadsafe-qt." >&5
+echo "${ECHO_T}instead of libqt), please specify the option --with-threadsafe-qt." >&6; }
+			{ echo "$as_me:$LINENO: result: The QT package can be found under the following URL:" >&5
+echo "${ECHO_T}The QT package can be found under the following URL:" >&6; }
+			{ echo "$as_me:$LINENO: result: http://www.troll.no/qt" >&5
+echo "${ECHO_T}http://www.troll.no/qt" >&6; }
+			{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+			{ echo "$as_me:$LINENO: result: Note: BALL requires QT 4.x! QT3 is no longer supported." >&5
+echo "${ECHO_T}Note: BALL requires QT 4.x! QT3 is no longer supported." >&6; }
+
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+	{ echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6; }
+	{ echo "$as_me:$LINENO: result: of the above error message, please contact the BALL mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the BALL mailing list" >&6; }
+	{ echo "$as_me:$LINENO: result: or the BALL developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the BALL developers. Please enclose the file 'conf.diag.tar'" >&6; }
+	{ echo "$as_me:$LINENO: result: which has been created in source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in source. It contains the relevant" >&6; }
+	{ echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6; }
+	{ echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6; }
+	{ echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6; }
+	{ echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6; }
+	{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+	FILES="configure configure.ac aclocal.m4 config.log"
+	if test -f config.h ; then FILES="$FILES config.h" ; fi
+	if test -f config.mak ; then FILES="$FILES config.mak" ; fi
+	if test -f common.mak ; then FILES="$FILES common.mak" ; fi
+	tar cf $TARFILE $FILES
+
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+		fi
+	fi
+
+
 	{ echo "$as_me:$LINENO: checking for libQtOpenGL" >&5
 echo $ECHO_N "checking for libQtOpenGL... $ECHO_C" >&6; }
 	if test "${QTDIR}" != "" ; then
@@ -21555,19 +21711,19 @@ echo "${ECHO_T}yes" >&6; }
 echo $ECHO_N "checking linking against QT libraries... $ECHO_C" >&6; }
 
 		if test "${QT_LIBPATH}" != "/usr/lib" ; then
-			QTQGL_LIBOPTS="-L${QT_LIBPATH} -lQtOpenGL -lQtGui -lQtCore -lQtTest"
-			QT_LIBOPTS="-L${QT_LIBPATH} -lQtOpenGL -lQtGui -lQtCore -lQtTest"
+			QTQGL_LIBOPTS="-L${QT_LIBPATH} -lQtOpenGL -lQtGui -lQtCore -lQtTest -lQtSql"
+			QT_LIBOPTS="-L${QT_LIBPATH} -lQtOpenGL -lQtGui -lQtCore -lQtTest -lQtSql"
 			if test "${OS}" = "Darwin" ; then
-				QTQGL_LIBOPTS="-F${QT_LIBPATH} -framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest"
-				QT_LIBOPTS="-F${QT_LIBPATH} -framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest"
+				QTQGL_LIBOPTS="-F${QT_LIBPATH} -framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest -framework QtSql"
+				QT_LIBOPTS="-F${QT_LIBPATH} -framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest -framework QtSql"
 			fi
 		else
 			QT_LIBPATH=""
-			QTQGL_LIBOPTS=" -lQtOpenGL -lQtGui -lQtCore -lQtTest"
-			QT_LIBOPTS="-lQtOpenGL -lQtGui -lQtCore -lQtTest"
+			QTQGL_LIBOPTS=" -lQtOpenGL -lQtGui -lQtCore -lQtTest -lQtSql"
+			QT_LIBOPTS="-lQtOpenGL -lQtGui -lQtCore -lQtTest -lQtSql"
 			if test "${OS}" = "Darwin" ; then
-				QTQGL_LIBOPTS="-framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest"
-				QT_LIBOPTS="-framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest"
+				QTQGL_LIBOPTS="-framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest -framework QtSql"
+				QT_LIBOPTS="-framework QtOpenGL -framework QtGui -framework QtCore -framework QtTest -framework QtSql"
 			fi
 		fi
 
