added: test for inline functions as arguments to template functions (SGI-CC problem)

diff --git a/source/configure b/source/configure
--- a/source/configure
+++ b/source/configure
@@ -5163,6 +5163,54 @@ echo "$as_me: error: aborted" >&2;}
 	fi
 
 
+	echo "$as_me:$LINENO: checking for inline template function arguments" >&5
+echo $ECHO_N "checking for inline template function arguments... $ECHO_C" >&6
+	BALL_HAS_INLINE_TPL_ARGS=no
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+			template <int i>
+			inline double foo(double x){ return i * x; }
+
+			typedef double (*Function)(double);
+
+			template <Function F>
+			inline double bar(double x) { return F(x); }
+
+int
+main ()
+{
+
+			double d = bar< foo<3> >(2.0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  BALL_HAS_INLINE_TPL_ARGS=yes
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: $BALL_HAS_INLINE_TPL_ARGS" >&5
+echo "${ECHO_T}$BALL_HAS_INLINE_TPL_ARGS" >&6
+
+
 	echo "$as_me:$LINENO: checking for ANSI compliant iostream" >&5
 echo $ECHO_N "checking for ANSI compliant iostream... $ECHO_C" >&6
 	BALL_HAS_ANSI_IOSTREAM=no
